#!/bin/bash
#
# This bash script needs jq and xml2json installed on your system
# 	sudo npm install xml2json -g
# 	sudo pacman -S jq
#
# Needed arguemnts for run are:
# 	1. Input filename
# 	2. Root tag of xml file
# 	3. Each splited file should have how much lines in it
# 	5. Start line
# 	6. Optional start count number
#
#	IMPORTANT: Optional parts should be used in order, you can not have 5 without 4 for now.
#

file_name=$1
root_tag=$2
step=$3
start=$4
if [ $5 = -1 ];then
	k=1
else
	k=$5
fi


mkdir -p $root_tag
mkdir -p $root_tag/json

line_number=1
lines_wrote=0
while read -r line
do
    if [ $line_number -gt $(( $start - 1 )) ];then
    	echo "$line" >> $root_tag/$root_tag\_$k.xml
	lines_wrote=$(( $lines_wrote + 1 ))
	if [ $lines_wrote = $step ];then
		echo "wrote $line_number to $(( $line_number + $step )) into $root_tag/$root_tag\_$k.xml" 
		lines_wrote=0
		k=$(( $k + 1 ))
	fi
    fi
    line_number=$(( $line_number + 1 ))

done < "$file_name"

#command to convert xml to json
#cat xml-spliter-temp.xml | xml2json | jq .$4.row > $5
